[platformio]

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38/platform-espressif32.zip
framework = arduino
monitor_speed = 115200
build_type = debug

lib_deps =
    https://github.com/mathertel/OneButton
    ; https://github.com/mhaberler/Improv-WiFi-Library.git
    symlink://../..
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DIMPROV_WIFI_BLE_ENABLED

[env:m5stack-nanoc6]
board = esp32-c6-devkitm-1
board_build.mcu = esp32c6
board_build.partitions = ota_nofs_4MB.csv
build_flags =
    ${env.build_flags}
    -DLED_BLUE=GPIO_NUM_7
    -DBUTTON_PIN=9

[env:m5stack-atoms3]
board = m5stack-atoms3
build_flags =
    ${env.build_flags}
    -DLED_BLUE=GPIO_NUM_1

[env:m5stamp-s3]
board = m5stack-stamps3
build_flags =
    ${env.build_flags}
    -DLED_BLUE=GPIO_NUM42  ; connect a led

[env:esp32p4_waveshare_devkit]
board = esp32-p4-evboard
board_build.partitions = default_16MB.csv
build_flags =
    ${env.build_flags}
    -DLED_BLUE=GPIO_NUM_23
